[project]
name = "mock-transmiter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flatbuffers>=25.12.19",
    "bless<=0.3.0",
    "bleak-winrt>=1.2.0",
]
